// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SQ-Jeepify-Monitor480

#include "ui.h"

void Ui_Init_Custom(lv_event_t * e)
{
	// Your code here
}

void Ui_Set_Prepare(lv_event_t * e)
{
	// Your code here
}

void Ui_Set_Leave(lv_event_t * e)
{
	// Your code here
}

void Ui_Set_WebSvr(lv_event_t * e)
{
	// Your code here
}

void Ui_Set_TogglePair(lv_event_t * e)
{
	// Your code here
}

void Ui_Set_Restart(lv_event_t * e)
{
	// Your code here
}

void Ui_Set_Reset(lv_event_t * e)
{
	// Your code here
}

void Ui_Set_ToggleDebug(lv_event_t * e)
{
	// Your code here
}

void Ui_Set_SavePeers(lv_event_t * e)
{
	// Your code here
}

void Ui_Peers_Prepare(lv_event_t * e)
{
	// Your code here
}

void Ui_Peers_Selected(lv_event_t * e)
{
	// Your code here
}

void Ui_JSON_Prepare(lv_event_t * e)
{
	// Your code here
}

void Ui_Peer_Loaded(lv_event_t * e)
{
	// Your code here
}

void Ui_Peer_Next(lv_event_t * e)
{
	// Your code here
}

void Ui_Peer_Last(lv_event_t * e)
{
	// Your code here
}

void Ui_Peer_Restart(lv_event_t * e)
{
	// Your code here
}

void Ui_Peer_Reset(lv_event_t * e)
{
	// Your code here
}

void Ui_Peer_ToggleSleep(lv_event_t * e)
{
	// Your code here
}

void Ui_Peer_ToggleDemo(lv_event_t * e)
{
	// Your code here
}

void Ui_Peer_Delete(lv_event_t * e)
{
	// Your code here
}

void Ui_Eichen_Start(lv_event_t * e)
{
	// Your code here
}

void Ui_Volt_Prepare(lv_event_t * e)
{
	// Your code here
}

void Ui_Volt_Start(lv_event_t * e)
{
	// Your code here
}

void Ui_Multi_Unload(lv_event_t * e)
{
	// Your code here
}

void Ui_Multi_Next(lv_event_t * e)
{
	// Your code here
}

void Ui_Multi_Prev(lv_event_t * e)
{
	// Your code here
}
